version: '3.8'

services:
  # Backend API Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      - MONGO_URL="mongodb+srv://praneeth:praneeth@basicnodeconnect.x8dsf.mongodb.net/TodoApp?retryWrites=true&w=majority&appName=BasicNodeConnect"
    ports:
      - "3000:3000"

  # Angular Client Service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - api
    ports:
      - "80:80"
